/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pruebagradle;

public class App {
    public String getGreeting() {
        return "Prueba Gradle en java !";
    }
 
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
